"""
This type stub file was generated by pyright.
"""

import sys
from types import SimpleNamespace
from . import jupyter, non_tty, tty, void

if sys.platform == 'win32':
    ...
def get_void(): # -> SimpleNamespace:
    ...

def get_term(file=..., force_tty=..., cols=...): # -> SimpleNamespace:
    ...

