[tool.ruff]
# Enable the pycodestyle (`E`), Pyflakes (`F`), and isort (`I`) rules
select = ["E", "F", "I"]
# Also add flake8-bugbear (`B`) and flake8-docstrings (`D`)
extend-select = ["B", "D"]

# Exclude a variety of commonly ignored directories
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

# Allow unused variables when underscore-prefixed
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Allow autofix for all enabled rules (when `--fix`) is provided
fixable = ["ALL"]
unfixable = []

# Same line length as Black
line-length = 88

# Allow imports to be sorted in groups
target-version = "py39"

[tool.ruff.mccabe]
# Flag functions with a complexity higher than 10
max-complexity = 10

[tool.ruff.isort]
known-third-party = ["requests", "click", "alive_progress", "dotenv", "nox"]

[tool.ruff.per-file-ignores]
# Allow assert statements and magic methods in tests
"tests/*_test.py" = ["S101", "D104"]
# Ignore docstring requirements for simple scripts
"noxfile.py" = ["D"]