"""
This type stub file was generated by pyright.
"""

"""
This module must always be importable, even without the required libs for install!
It's because I import metadata from main init, directly in setup.py, which imports this.
"""
ERROR = ...
Config = ...
def create_config(): # -> Callable[..., Config]:
    ...

config_handler = ...
